apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: blog
data:
  config: |
    server {
        listen       80;
        server_name  {{ .Values.host }};
        root   /app/public;
        index  index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location /grafana/ {
            proxy_pass http://grafana-service:3000;
        }

        location ~ \.php$ {
            fastcgi_pass php-service:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: blog
data:
  config: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node_exporter_metrics'
        scrape_interval: 5s
        static_configs:
          - targets: ['{{ .Values.ip }}:9100']
