apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: blog
spec:
  {{- if .Values.tls }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: secret-tls
  {{- end }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-service
              servicePort: 80
