name: PHP-CS-Fixer

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: baijunyao/php:7.4-local
      volumes:
        - .:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
      - name: PHP CS Fixer
        run: |
          ./vendor/bin/php-cs-fixer fix --verbose --show-progress=dots --dry-run --diff
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@v2.2.0
        if: always()
        with:
          channel: CEWJP77BP
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
          job_context: ${{ toJson(job) }}
