name: PHPStan

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: baijunyao/php:7.4-local
      volumes:
        - .:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Initial
        run: |
          cp .env.actions .env
          composer install
      - name: PHPStan
        run: |
          ./vendor/bin/phpstan analyse --ansi
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@v2.2.0
        if: always()
        with:
          channel: CEWJP77BP
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
          job_context: ${{ toJson(job) }}
